server:
  port: 8080

spring:
  application:
    name: ComNCheck
  datasource:
    driver-class-name: org.h2.Driver
    url: ${H2_DB_URL}  #url: 'jdbc:h2:~/test' -> H2 DB 연결 주소 (Embedded Mode)
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}